src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher
  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    begin
      request.format.to_sym != :xml
    rescue ArgumentError => e
      raise InvalidRequestFormat.new e.to_s
    end
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    # Rails.logger.debug "MATCHES #{format}"
    format == :xml || format == :json
  end
end

OBSApi::Application.routes.draw do
  cons = {
    arch:       %r{[^\/]*},
    binary:     %r{[^\/]*},
    filename:   %r{[^\/]*},
    id:         %r{\d*},
    login:      %r{[^\/]*},
    package:    %r{[^\/]*},
    project:    %r{[^\/]*},
    repository: %r{[^\/]*},
    service:    %r{\w[^\/]*},
    title:      %r{[^\/]*},
    user:       %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
      get 'main/add_news_dialog' => :add_news_dialog
      post 'main/add_news' => :add_news
      get 'main/delete_message_dialog' => :delete_message_dialog
      post 'main/delete_message' => :delete_message
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, as: :news_feed
      get 'main/latest_updates' => :latest_updates, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons,  as: 'index'
      end
    end

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
      get 'configuration/interconnect' => :interconnect
      post 'configuration/interconnect' => :create_interconnect
    end

    controller 'webui/notifications' do
      get 'notifications' => :index
      patch 'notifications' => :bulk_update, as: 'bulk_update_notifications'
    end

    controller 'webui/architectures' do
      get 'architectures' => :index
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: 'bulk_update_availability'
    end

    controller 'webui/driver_update' do
      get 'driver_update/create' => :create
      get 'driver_update/edit' => :edit
      post 'driver_update/save' => :save
      get 'driver_update/binaries' => :binaries
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events
    end

    controller 'webui/package' do
      get 'package/show/(:project/(:package))' => :show, as: 'package_show', constraints: cons
      get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
      get 'package/dependency/:project/:package' => :dependency, constraints: cons
      get 'package/binary/:project/:package' => :binary, constraints: cons, as: 'package_binary'
      get 'package/binaries/:project/:package' => :binaries, constraints: cons, as: 'package_binaries'
      get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
      get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
      get 'package/statistics/:project/:package' => :statistics, as: 'package_statistics', constraints: cons
      get 'package/commit/:project/:package' => :commit, as: 'package_commit', constraints: cons
      get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
      get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
      post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
      get 'package/add_person/:project/:package' => :add_person, constraints: cons
      get 'package/add_group/:project/:package' => :add_group, constraints: cons
      get 'package/rdiff/(:project/(:package))' => :rdiff, constraints: cons
      get 'package/wizard_new/:project' => :wizard_new, constraints: cons
      get 'package/wizard/:project/:package' => :wizard, constraints: cons
      post 'package/save_new/:project' => :save_new, constraints: cons
      get 'package/branch_dialog/:project/:package' => :branch_dialog, constraints: cons
      post 'package/branch/:project/:package' => :branch, constraints: cons
      post 'package/save_new_link/:project' => :save_new_link, constraints: cons
      post 'package/save/:project/:package' => :save, constraints: cons
      get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
      post 'package/remove/:project/:package' => :remove, constraints: cons
      get 'package/add_file/:project/:package' => :add_file, constraints: cons
      post 'package/save_file/:project/:package' => :save_file, constraints: cons
      post 'package/remove_file/:project/:package' => :remove_file, constraints: cons
      post 'package/save_person/:project/:package' => :save_person, constraints: cons
      post 'package/save_group/:project/:package' => :save_group, constraints: cons
      post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
      get 'package/view_file/(:project/(:package/(:filename)))' => :view_file, constraints: cons, as: 'package_view_file'
      get 'package/live_build_log/(:project/(:package/(:repository/(:arch))))' => :live_build_log, constraints: cons, as: 'package_live_build_log'
      get 'package/update_build_log/:project/:package' => :update_build_log, constraints: cons
      get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
      delete 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
      delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
      get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
      get 'package/buildresult' => :buildresult, constraints: cons
      get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
      get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
      get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
      post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
      # compat route
      get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
      get 'package/edit/:project/:package' => :edit, constraints: cons
      get 'package/repositories/:project/:package' => :repositories, constraints: cons
      post 'package/flag/:project/:package' => :create_flag, constraints: cons
      post 'project/flag/:project/:package/:flag' => :toggle_flag, constraints: cons
      delete 'project/flag/:project/:package/:flag' => :remove_flag, constraints: cons

      get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
      # compat route
      get 'package/files/:project/:package' => :show, constraints: cons
      post 'package/comments/:project/:package' => :save_comment, constraints: cons
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save' => :save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/get_issue_sum' => :get_issue_sum
      get 'patchinfo/delete_dialog' => :delete_dialog
    end

    controller 'webui/project' do
      get 'project/' => :index, as: 'projects'
      get 'project/list_public' => :index
      get 'project/list_all' => :index, show_all: true
      get 'project/list' => :index
      get 'project/autocomplete_projects' => :autocomplete_projects
      get 'project/autocomplete_incidents' => :autocomplete_incidents
      get 'project/autocomplete_packages' => :autocomplete_packages
      get 'project/autocomplete_repositories' => :autocomplete_repositories
      get 'project/users/:project' => :users, constraints: cons, as: 'project_users'
      get 'project/subprojects/:project' => :subprojects, constraints: cons, as: 'project_subprojects'
      get 'project/attributes/:project', to: redirect('/attribs/%{project}'), constraints: cons
      post 'project/new_incident' => :new_incident
      get 'project/new_package/:project' => :new_package, constraints: cons
      get 'project/new_package_branch/:project' => :new_package_branch, constraints: cons
      get 'project/incident_request_dialog' => :incident_request_dialog
      post 'project/new_incident_request' => :new_incident_request
      get 'project/release_request_dialog' => :release_request_dialog
      post 'project/new_release_request/(:project)' => :new_release_request, constraints: cons
      get 'project/show/(:project)' => :show, constraints: cons, as: 'project_show'
      get 'project/packages_simple/:project' => :packages_simple, constraints: cons
      get 'project/linking_projects/:project' => :linking_projects, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :add_repository_from_default_list, constraints: cons

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  # Apidocs is insensitive static information, no login needed therefore
  skip_before_filter :extract_user

  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + "/index.html"
    if File.exist?(filename)
      render :file => filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location'] }. Did you create the apidocs?"
      flash[:error] = "Unable to load API documentation."
      redirect_back_or_to root_path
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path( File.join(CONFIG['schema_location'], filename) )
    if File.exist?( file )
      send_file( file, :type => "text/xml", :disposition => "inline" )
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back_or_to :controller => 'apidocs', :action => 'index'
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_filter :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def bulk_update_availability
    all_valid = true
    params[:archs].each do |name, value|
      arch = Architecture.find_by(name: name)
      arch.available = value
      all_valid &&= arch.save
    end

    ::Configuration.write_to_backend

    respond_to do |format|
      if all_valid
        format.html { redirect_to architectures_path, notice: 'Architectures successfully updated.' }
      else
        format.html { redirect_to :back, error: 'Not all architectures could be saved' }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_filter :set_container, :only => [:index, :new, :edit]
  before_filter :set_attribute, :only => [:update, :destroy]
  before_filter :set_attribute_by_name, :only => [:edit]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, :except => :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end
    authorize @attribute, :create?
  end

  def edit
    authorize @attribute
    if @attribute.attrib_type.value_count and ( @attribute.attrib_type.value_count > @attribute.values.length )
      ( @attribute.attrib_type.value_count - @attribute.values.length ).times do
        @attribute.values.build(attrib: @attribute)
      end
    end
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s,
                                      :attribute => @attribute.fullname),
                    notice: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s),
                    notice: 'Attribute was successfully created.'
      end
    else
      redirect_to :back, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}"
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      redirect_to edit_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s, :attribute => @attribute.fullname),
                  notice: 'Attribute was successfully updated.'
    else
      redirect_to :back, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_to :back, notice: 'Attribute sucessfully deleted!'
  end

  private

  def set_container
    required_parameters :project
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIException
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to :controller => 'project' and return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIException
        redirect_to project_show_path(@project.to_s), error: "Package #{params[:package]} not found" and return
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute_by_name
    @attribute = Attrib.find_by_container_and_fullname( @container, params[:attribute] )
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of? Package
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of? Project
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/comments_controller.rb
class Webui::CommentsController < Webui::WebuiController
  def destroy
    comment = Comment.find(params[:id])
    unless comment.check_delete_permissions
      flash[:error] = 'No permissions to delete comment'
      redirect_to :back
      return
    end
    comment.blank_or_destroy

    respond_to do |format|
      format.js { render json: 'ok' }
      format.html do
        flash[:notice] = 'Comment deleted successfully'
      end
    end
    redirect_to :back
  end
end

src/api/app/controllers/webui/configuration_controller.rb
class Webui::ConfigurationController < Webui::WebuiController
  before_filter :require_admin
  before_filter :set_configuration, only: [:update]
  before_filter :require_available_architectures, only: [:index]

  def index; end

  def interconnect; end

  def create_interconnect
    @project = RemoteProject.new(project_params)

    if @project.valid? && @project.store
      flash[:notice] = "Project '#{@project.name}' was created successfully"
      logger.debug "New remote project with url #{@project.remoteurl}"
      redirect_to controller: :project, action: 'show', project: @project.name
    else
      redirect_to :back, error: "Project can't be saved: #{@project.errors.full_messages.to_sentence}"
    end
  end

  def update
    respond_to do |format|
      if @configuration.update(configuration_params)
        format.html { redirect_to configuration_path, notice: 'Configuration was successfully updated.' }
      else
        format.html { redirect_to :back, error: "Configuration can't be saved: #{@configuration.errors.full_messages.to_sentence}" }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :title, :remoteurl, :description)
    end

    def configuration_params
      params.require(:configuration).permit(:name, :title, :description)
    end

    def set_configuration
      @configuration = ::Configuration.first
    end
end

src/api/app/views/webui/project/_buildstatus.html.erb
<div id="project_buildstatus">
  <% if @buildresult.blank? %>
      <% if @project.remoteurl %>
          <p><i>This project is just used to get referenced for using remote resources. </i></p>
      <% elsif @project.repositories.count == 0 %>
          <p><i>This project currently has
            no <%= link_to "build targets", :controller => :project, :action => 'add_repository_from_default_list', :project => @project %>
            defined. </i></p>
      <% else %>
          <p><i>No build result available</i></p>
      <% end %>
  <% else %>
      <table title="Repositories" class="repostatus">
        <% @buildresult.each do |repo, archarray| %>
            <% index = 0
               srepo = truncate(repo, :length => 17)
               archarray.each do |arch, counts| %>
                <tr>
                  <% if index == 0 %>
                      <td class="repo nowrap" rowspan="<%= archarray.length %>">
                        <%= link_to(elide(srepo, 26), {:action => 'repository_state', :project => @project.name, :repository => repo}, {:title => "Repository #{srepo}"}) %>
                      </td>
                      <% index += 1 %>
                  <% end %>
                  <td class="nowrap">
                    <%= repo_status_icon(@repostatushash[repo][arch], @repostatusdetailshash[repo][arch])%> <%= arch %>
                  </td>
                  <td style="width: 1%">
                    <% counts.each do |code, count| %>
                        <%= link_to("#{code}: #{count}", {:action => :monitor, valid_xml_id('repo_' + repo) => 1,
                                                          'arch_' + arch => 1, :project => params[:project], code => 1, :defaults => 0}, :rel => 'nofollow', :class => 'nowrap') %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
        <% end %>
      </table>
  <% end %>
</div>

src/api/app/views/webui/project/_delete_dialog.html.erb
  <div class="dialog" id="disable_mask"></div>
  <div class="dialog darkgrey_box">
    <div class="box box-shadow">
      <h2 class="box-header">Delete Confirmation</h2>
      <div class="dialog-content">
        <p>Do you really want to delete <%= project_or_package_link project: @project.name %>?</p>
  
        <%= form_tag({:controller => 'project', :action => 'destroy'}, :method => 'delete') do %>
          <%= hidden_field_tag(:project, @project) %>
          <% if @linking_projects and @linking_projects.length > 0 %>
            <p>Other projects still have source links to this project:</p>
            <ul>
              <% @linking_projects.each do |link| %>
                <li><%= link_to(elide(link, 40), :controller => 'project', :action => 'show', :project => link) %></li>
              <% end %>
            </ul>
          <% end %>
  
          <div class="dialog-buttons">
            <%= submit_tag('Ok') %>
            <%= remove_dialog_tag('Cancel') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

src/api/app/views/webui/project/_edit_comment.html.erb
<div>

<% if @error %>
  <%= sprite_tag 'dialog-warning' %>
  <%= @error %>
<% end %>

<%= show_status_comment( @comment, @package, true, [] ) %>

src/api/app/views/webui/project/_incident_request_dialog.html.erb
  <div class="dialog" id="disable_mask"></div>
  <div class="dialog darkgrey_box">
    <div class="box box-shadow">
      <h2 class="box-header">Submit as Update</h2>
      <div class="dialog-content">
        <p>This will submit your project as a Maintenance Incident Request.</p>
        <%= form_tag({:controller => 'project', :action => 'new_incident_request'}, :method => :post) do %>
          <%= hidden_field_tag(:project, @project) %>
          <p>
            <%= label_tag(:sourceproject, 'Project submitted as Update:') %><br/>
            <%= text_field_tag(:sourceproject, format_projectname(@project.name, User.current.login), :size => 40, :disabled => true) %><br/>
  
            <%= label_tag(:sourceproject, 'Release Targets:') %><br/>
            <% @releasetargets.each do |rt| %>
              <%= text_field_tag(:releasetarget, rt, :size=> 40, :disabled => true) %>
                <br/>
            <% end %>
            <%= label_tag(:description, 'Description:') %><br/>
            <%= text_area_tag(:description, '', :size => '40x3') %>
          </p>
          <div class="dialog-buttons">
            <%= submit_tag('Ok') %>
            <%= remove_dialog_tag('Cancel') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

src/api/app/views/webui/project/_packages_table.html.erb
<% content_for :ready_function do %>
    $( "#packages" ).tabs();
<% end %>

<div class="grid_10 alpha box box-shadow">

  <div id="packages">
    <div class="box-header header-tabs">
      <ul>
        <li><a href="#raw_packages" title="Packages directly in the project">Packages (<%= @packages.length %>)</a>
        </li>
        <% if @ipackages.present? %>
            <li>
              <a href="#inherited_packages"
                 title="Inherited Packages">Inherited Packages (<%= @ipackages.length %>)</a>
            </li>
        <% end %>
      </ul>
    </div>
    <div id="raw_packages" class="tab">

      <% packageurl = url_for(controller: 'package', action: 'show', project: @project, package: 'REPLACEIT') %>
      <% if @packages.present? %>
          <% cache [packageurl, Digest::MD5.hexdigest(@packages.join)] do %>
              <div id="packages_table_wrapper" data-url="<%= packageurl %>">
                <%= javascript_tag do %>
                    var packages = [ <%= escape_list(@packages) %> ];
                    renderPackagesTable("packages_table_wrapper", packages);
                <% end %>
              </div>
          <% end %>
      <% else %>
          <p><i>This project does not contain any packages</i></p>
      <% end %>

      <% if @project.kind_of?(Project) && User.current.can_modify_project?(@project) %>
          <% if !@project.defines_remote_instance? && !(@is_incident_project && !@packages.blank? && @has_patchinfo && @open_release_requests.length == 0) && !@is_maintenance_project %>
              <ul class="horizontal-list">
                <li>
                  <%= link_to(sprited_text('package_add', 'Create package'), controller: 'project', action: 'new_package', project: @project) %>
                </li>
                <li>
                  <%= link_to sprited_text('package_link', 'Branch existing package'), controller: :project, action: :new_package_branch, project: @project %>
                </li>
              </ul>
          <% end %>
      <% end %>
    </div>

    <% if @ipackages.present? %>
        <div id="inherited_packages" class="tab">
          <% packageurl = url_for(controller: 'package', action: 'show', project: @project, package: 'REPLACEPKG') %>
          <% cache [packageurl, Digest::MD5.hexdigest(@ipackages.join)] do %>
              <div id="ipackages_wrapper" data-url="<%= packageurl %>">
                <%= javascript_tag do %>
                    var ipackages = [ <%= escape_nested_list(@ipackages) %> ];
                    renderPackagesProjectsTable({packages: ipackages, name: 'ipackages_wrapper'});
                <% end %>
              </div>
          <% end %>
        </div>
    <% end %>

    <% if @packages.present? && @ipackages.present? %>
      <%= javascript_tag do %>
        $('#packages_table_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#ipackages_wrapper_table').dataTable().fnFilter( $(this).val());
        });

        $('#ipackages_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#packages_table_wrapper_table').dataTable().fnFilter( $(this).val());
        });
      <% end %>
    <% end %>
  </div>
  <% if @packages.present? && @ipackages.present? %>
    <%= javascript_tag do %>
        $('#packages_table_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#ipackages_wrapper_table').dataTable().fnFilter( $(this).val());
        });
        $('#ipackages_wrapper_table_filter input:first-of-type').on("keyup paste", function() {
          $('#packages_table_wrapper_table').dataTable().fnFilter( $(this).val());
        });
    <% end %>
  <% end %>
  <noscript>
    <%= link_to 'Packages', action: 'packages_simple', project: @project %>
  </noscript>
</div>

src/api/app/views/webui/project/_remove_target_request_dialog.html.erb
  <div class="dialog" id="disable_mask"></div>
  <div class="dialog darkgrey_box">
    <div class="box box-shadow">
      <h2 class="box-header">Create Repository Delete Request</h2>
      <div class="dialog-content">
        <p>Do you really want to request the deletion of repository <i><%= params[:repository] %></i>?</p>
  
        <%= form_tag({:controller => 'project', :action => 'remove_target_request'}, :method => 'post') do %>
          <%= hidden_field_tag(:project, params[:project]) %>
          <%= hidden_field_tag(:repository, params[:repository]) %>
          <p>
            <%= label_tag(:description, 'Description:') %><br/>
            <%= text_area_tag(:description, '', :size => '40x3') %>
          </p>
          <div class="dialog-buttons">
            <%= submit_tag('Ok') %>
            <%= remove_dialog_tag('Cancel') %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

src/api/app/views/webui/project/list.html.erb
<% @pagetitle = "Public Projects" %>
<%
   @crumb_list = %w(Projects)
-%>

<% unless @important_projects.blank? %>
    <h3>Main Projects</h3>
    <% for project in @important_projects -%>
        <p class='main-project'>
          <%= link_to project[0], action: :show, project: project[0] %>:
          <%= project[1] %>
        </p>
    <% end -%>
<% end -%>

<h3><%= @pagetitle %></h3>
<div style="display: inline">
  <p>
    <% if @show_all %>
      <%= link_to "Exclude home projects", projects_path %>
    <% else %>
      <%= link_to "Include home projects", projects_path(show_all: true) %>
    <% end %>
    <% unless User.current.is_nobody? %>
      <span style="float: right">
        <%= link_to sprite_tag('brick_add', title: 'Create new project') + 'Create new project', :controller => :project, :action => :new %>
      </span>
    <% end %>
  </p>
</div>

<% cachekey = Digest::MD5.hexdigest(@projects.join)
   projecturl = url_for(controller: 'project', action: 'show', project: 'REPLACEIT')
%>

<div id="project_list">
  <% if @projects.blank? %>
      <p><i>No projects found</i></p>
  <% else %>
      <div id="projects_table_wrapper" data-url="<%= projecturl %>">

        <% content_for :head_javascript do %>
            <% cache ['list_public_arrays', cachekey] do %>
                var main_projects = [ <%= escape_nested_list(@projects) %> ];
                var excl_projects = [];
            <% end %>
        <% end %>
        <% content_for :ready_function do %>
            renderProjectsTable();
        <% end %>
      </div>
  <% end %>

</div>

src/api/app/views/webui/project/maintenance_incidents.html.erb
<% @pagetitle = 'Maintenance Incidents' %>
<% project_bread_crumb @pagetitle %>

<%= render :partial => 'tabs' %>

<h3>
  Maintenance incidents <span id="incident_count"><%= "(#{@incidents.count})" %></span>
</h3>

<div id="incident_display" class="clearfix">
  <% if @incidents.exists? %>
    <%= render(:partial => 'incident_table', :locals => { :incidents => @incidents }) %>
  <% else %>
    <p><i>No incidents.</i></p>
  <% end %>
</div>

src/api/app/views/webui/project/patchinfo.html.erb
<% @pagetitle = "Patchinfos of Project #{@project}" %>
<% project_bread_crumb( 'Patchinfo' ) -%>

<%= render :partial => 'tabs' %>

<h3>
  Patchinfos for project <%= @project %> 
</h3>

<% if @patchinfo.empty? %>
<p><i>This project does not contain any patchinfo yet.</i></p>
<% else %>

<div id="pkg_container">
  <h3>Patchinfo</h3>
  <p>
    <% @patchinfo.each do |package| -%>
      <%= link_to package, { :controller => 'patchinfo', :action => :edit_patchinfo, :project=> @project, :package => package}, :class => 'nowrap' %>
    <% end%>
  </p>
</div>

<% end %>