src/api/config/routes.rb
# we take everything here that is not XML - the default mimetype is xml though
class WebuiMatcher
  class InvalidRequestFormat < APIException
  end

  def self.matches?(request)
    begin
      request.format.to_sym != :xml
    rescue ArgumentError => e
      raise InvalidRequestFormat.new e.to_s
    end
  end
end

# here we take everything that is XML, JSON or osc ;)
class APIMatcher
  def self.matches?(request)
    format = request.format.to_sym || :xml
    # Rails.logger.debug "MATCHES #{format}"
    format == :xml || format == :json
  end
end

OBSApi::Application.routes.draw do
  cons = {
    arch:       %r{[^\/]*},
    binary:     %r{[^\/]*},
    filename:   %r{[^\/]*},
    id:         %r{\d*},
    login:      %r{[^\/]*},
    package:    %r{[^\/]*},
    project:    %r{[^\/]*},
    repository: %r{[^\/]*},
    service:    %r{\w[^\/]*},
    title:      %r{[^\/]*},
    user:       %r{[^\/]*}
  }

  constraints(WebuiMatcher) do
    root 'webui/main#index'

    controller 'webui/main' do
      get 'main/systemstatus' => :systemstatus
      get 'main/add_news_dialog' => :add_news_dialog
      post 'main/add_news' => :add_news
      get 'main/delete_message_dialog' => :delete_message_dialog
      post 'main/delete_message' => :delete_message
    end

    controller 'webui/feeds' do
      get 'main/news' => :news, as: :news_feed
      get 'main/latest_updates' => :latest_updates, as: :latest_updates_feed
      get 'project/latest_commits/:project' => :commits, defaults: { format: 'atom' }, constraints: cons, as: 'commits_feed'
    end

    resources :attribs, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/attribute' do
      collection do
        get ':project(/:package)/new' => :new, constraints: cons, as: 'new'
        get ':project(/:package)/:attribute/edit' => :edit, constraints: cons, as: 'edit'
        get ':project(/:package)' => :index, constraints: cons,  as: 'index'
      end
    end

    resources :download_repositories, constraints: cons, only: [:create, :update, :destroy], controller: 'webui/download_on_demand'

    controller 'webui/configuration' do
      get 'configuration' => :index
      patch 'configuration' => :update
      get 'configuration/interconnect' => :interconnect
      post 'configuration/interconnect' => :create_interconnect
    end

    controller 'webui/notifications' do
      get 'notifications' => :index
      patch 'notifications' => :bulk_update, as: 'bulk_update_notifications'
    end

    controller 'webui/architectures' do
      get 'architectures' => :index
      patch 'architectures/bulk_update_availability' => :bulk_update_availability, as: 'bulk_update_availability'
    end

    controller 'webui/driver_update' do
      get 'driver_update/create' => :create
      get 'driver_update/edit' => :edit
      post 'driver_update/save' => :save
      get 'driver_update/binaries' => :binaries
    end

    controller 'webui/monitor' do
      get 'monitor/' => :index
      get 'monitor/old' => :old
      get 'monitor/update_building' => :update_building
      get 'monitor/events' => :events
    end

    controller 'webui/package' do
      get 'package/show/(:project/(:package))' => :show, as: 'package_show', constraints: cons
      get 'package/linking_packages/:project/:package' => :linking_packages, constraints: cons
      get 'package/dependency/:project/:package' => :dependency, constraints: cons
      get 'package/binary/:project/:package' => :binary, constraints: cons, as: 'package_binary'
      get 'package/binaries/:project/:package' => :binaries, constraints: cons, as: 'package_binaries'
      get 'package/users/:project/:package' => :users, as: 'package_users', constraints: cons
      get 'package/requests/:project/:package' => :requests, as: 'package_requests', constraints: cons
      get 'package/statistics/:project/:package' => :statistics, as: 'package_statistics', constraints: cons
      get 'package/commit/:project/:package' => :commit, as: 'package_commit', constraints: cons
      get 'package/revisions/:project/:package' => :revisions, constraints: cons, as: 'package_view_revisions'
      get 'package/submit_request_dialog/:project/:package' => :submit_request_dialog, constraints: cons
      post 'package/submit_request/:project/:package' => :submit_request, constraints: cons
      get 'package/add_person/:project/:package' => :add_person, constraints: cons
      get 'package/add_group/:project/:package' => :add_group, constraints: cons
      get 'package/rdiff/(:project/(:package))' => :rdiff, constraints: cons
      get 'package/wizard_new/:project' => :wizard_new, constraints: cons
      get 'package/wizard/:project/:package' => :wizard, constraints: cons
      post 'package/save_new/:project' => :save_new, constraints: cons
      get 'package/branch_dialog/:project/:package' => :branch_dialog, constraints: cons
      post 'package/branch/:project/:package' => :branch, constraints: cons
      post 'package/save_new_link/:project' => :save_new_link, constraints: cons
      post 'package/save/:project/:package' => :save, constraints: cons
      get 'package/delete_dialog/:project/:package' => :delete_dialog, constraints: cons
      post 'package/remove/:project/:package' => :remove, constraints: cons
      get 'package/add_file/:project/:package' => :add_file, constraints: cons
      post 'package/save_file/:project/:package' => :save_file, constraints: cons
      post 'package/remove_file/:project/:package' => :remove_file, constraints: cons
      post 'package/save_person/:project/:package' => :save_person, constraints: cons
      post 'package/save_group/:project/:package' => :save_group, constraints: cons
      post 'package/remove_role/:project/:package' => :remove_role, constraints: cons
      get 'package/view_file/(:project/(:package/(:filename)))' => :view_file, constraints: cons, as: 'package_view_file'
      get 'package/live_build_log/(:project/(:package/(:repository/(:arch))))' => :live_build_log, constraints: cons, as: 'package_live_build_log'
      get 'package/update_build_log/:project/:package' => :update_build_log, constraints: cons
      get 'package/abort_build/:project/:package' => :abort_build, constraints: cons
      delete 'package/trigger_rebuild/:project/:package' => :trigger_rebuild, constraints: cons
      delete 'package/wipe_binaries/:project/:package' => :wipe_binaries, constraints: cons
      get 'package/devel_project/:project/:package' => :devel_project, constraints: cons
      get 'package/buildresult' => :buildresult, constraints: cons
      get 'package/rpmlint_result' => :rpmlint_result, constraints: cons
      get 'package/rpmlint_log' => :rpmlint_log, constraints: cons
      get 'package/meta/:project/:package' => :meta, constraints: cons, as: 'package_meta'
      post 'package/save_meta/:project/:package' => :save_meta, constraints: cons
      # compat route
      get 'package/attributes/:project/:package', to: redirect('/attribs/%{project}/%{package}'), constraints: cons
      get 'package/edit/:project/:package' => :edit, constraints: cons
      get 'package/repositories/:project/:package' => :repositories, constraints: cons
      post 'package/flag/:project/:package' => :create_flag, constraints: cons
      post 'project/flag/:project/:package/:flag' => :toggle_flag, constraints: cons
      delete 'project/flag/:project/:package/:flag' => :remove_flag, constraints: cons

      get 'package/import_spec/:project/:package' => :import_spec, constraints: cons
      # compat route
      get 'package/files/:project/:package' => :show, constraints: cons
      post 'package/comments/:project/:package' => :save_comment, constraints: cons
    end

    controller 'webui/patchinfo' do
      post 'patchinfo/new_patchinfo' => :new_patchinfo
      post 'patchinfo/updatepatchinfo' => :updatepatchinfo
      get 'patchinfo/edit_patchinfo' => :edit_patchinfo
      get 'patchinfo/show/:project/:package' => :show, as: 'patchinfo_show', constraints: cons
      get 'patchinfo/read_patchinfo' => :read_patchinfo
      post 'patchinfo/save' => :save
      post 'patchinfo/remove' => :remove
      get 'patchinfo/new_tracker' => :new_tracker
      get 'patchinfo/get_issue_sum' => :get_issue_sum
      get 'patchinfo/delete_dialog' => :delete_dialog
    end

    controller 'webui/project' do
      get 'project/' => :index, as: 'projects'
      get 'project/list_public' => :index
      get 'project/list_all' => :index, show_all: true
      get 'project/list' => :index
      get 'project/autocomplete_projects' => :autocomplete_projects
      get 'project/autocomplete_incidents' => :autocomplete_incidents
      get 'project/autocomplete_packages' => :autocomplete_packages
      get 'project/autocomplete_repositories' => :autocomplete_repositories
      get 'project/users/:project' => :users, constraints: cons, as: 'project_users'
      get 'project/subprojects/:project' => :subprojects, constraints: cons, as: 'project_subprojects'
      get 'project/attributes/:project', to: redirect('/attribs/%{project}'), constraints: cons
      post 'project/new_incident' => :new_incident
      get 'project/new_package/:project' => :new_package, constraints: cons
      get 'project/new_package_branch/:project' => :new_package_branch, constraints: cons
      get 'project/incident_request_dialog' => :incident_request_dialog
      post 'project/new_incident_request' => :new_incident_request
      get 'project/release_request_dialog' => :release_request_dialog
      post 'project/new_release_request/(:project)' => :new_release_request, constraints: cons
      get 'project/show/(:project)' => :show, constraints: cons, as: 'project_show'
      get 'project/packages_simple/:project' => :packages_simple, constraints: cons
      get 'project/linking_projects/:project' => :linking_projects, constraints: cons
      get 'project/add_repository_from_default_list/:project' => :add_repository_from_default_list, constraints: cons

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  # Apidocs is insensitive static information, no login needed therefore
  skip_before_filter :extract_user

  def index
    filename = File.expand_path(CONFIG['apidocs_location']) + "/index.html"
    if File.exist?(filename)
      render :file => filename, formats: [:html]
    else
      logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location'] }. Did you create the apidocs?"
      flash[:error] = "Unable to load API documentation."
      redirect_back_or_to root_path
    end
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path( File.join(CONFIG['schema_location'], filename) )
    if File.exist?( file )
      send_file( file, :type => "text/xml", :disposition => "inline" )
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back_or_to :controller => 'apidocs', :action => 'index'
    end
    return
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_filter :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def bulk_update_availability
    all_valid = true
    params[:archs].each do |name, value|
      arch = Architecture.find_by(name: name)
      arch.available = value
      all_valid &&= arch.save
    end

    ::Configuration.write_to_backend

    respond_to do |format|
      if all_valid
        format.html { redirect_to architectures_path, notice: 'Architectures successfully updated.' }
      else
        format.html { redirect_to :back, error: 'Not all architectures could be saved' }
      end
    end
  end
end

src/api/app/controllers/webui/attribute_controller.rb
class Webui::AttributeController < Webui::WebuiController
  helper :all
  before_filter :set_container, :only => [:index, :new, :edit]
  before_filter :set_attribute, :only => [:update, :destroy]
  before_filter :set_attribute_by_name, :only => [:edit]

  # raise an exception if authorize has not yet been called.
  after_action :verify_authorized, :except => :index

  helper 'webui/project'

  def index
    @attributes = @container.attribs
  end

  def new
    if @package
      @attribute = Attrib.new(package_id: @package.id)
    else
      @attribute = Attrib.new(project_id: @project.id)
    end
    authorize @attribute, :create?
  end

  def edit
    authorize @attribute
    if @attribute.attrib_type.value_count and ( @attribute.attrib_type.value_count > @attribute.values.length )
      ( @attribute.attrib_type.value_count - @attribute.values.length ).times do
        @attribute.values.build(attrib: @attribute)
      end
    end
  end

  def create
    @attribute = Attrib.new(attrib_params)

    authorize @attribute

    # build the default values
    if @attribute.attrib_type.value_count
      @attribute.attrib_type.value_count.times do
        @attribute.values.build(attrib: @attribute)
      end
    end

    if @attribute.save
      if @attribute.values_editable?
        redirect_to edit_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s,
                                      :attribute => @attribute.fullname),
                    notice: 'Attribute was successfully created.'
      else
        redirect_to index_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s),
                    notice: 'Attribute was successfully created.'
      end
    else
      redirect_to :back, error: "Saving attribute failed: #{@attribute.errors.full_messages.join(', ')}"
    end
  end

  def update
    authorize @attribute

    if @attribute.update(attrib_params)
      redirect_to edit_attribs_path(:project => @attribute.project.to_s, :package => @attribute.package.to_s, :attribute => @attribute.fullname),
                  notice: 'Attribute was successfully updated.'
    else
      redirect_to :back, error: "Updating attribute failed: #{@attribute.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    authorize @attribute

    @attribute.destroy
    redirect_to :back, notice: 'Attribute sucessfully deleted!'
  end

  private

  def set_container
    required_parameters :project
    begin
      @project = Project.get_by_name(params[:project])
    rescue APIException
      flash[:error] = "Project not found: #{params[:project]}"
      redirect_to :controller => 'project' and return
    end
    if params[:package]
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue APIException
        redirect_to project_show_path(@project.to_s), error: "Package #{params[:package]} not found" and return
      end
      @container = @package
    else
      @container = @project
    end
  end

  def set_attribute_by_name
    @attribute = Attrib.find_by_container_and_fullname( @container, params[:attribute] )
  end

  def set_attribute
    @attribute = Attrib.find(params[:id])
    if @attribute.container.instance_of? Package
      @package = @attribute.container
      @project = @package.project
    elsif @attribute.container.instance_of? Project
      @project = @attribute.container
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def attrib_params
    params.require(:attrib).permit(:attrib_type_id, :project_id, :package_id,
                                   values_attributes: [:id, :value, :position, :_destroy],
                                   issues_attributes: [:id, :name, :issue_tracker_id, :_destroy])
  end
end

src/api/app/controllers/webui/comments_controller.rb
class Webui::CommentsController < Webui::WebuiController
  def destroy
    comment = Comment.find(params[:id])
    unless comment.check_delete_permissions
      flash[:error] = 'No permissions to delete comment'
      redirect_to :back
      return
    end
    comment.blank_or_destroy

    respond_to do |format|
      format.js { render json: 'ok' }
      format.html do
        flash[:notice] = 'Comment deleted successfully'
      end
    end
    redirect_to :back
  end
end

src/api/app/controllers/webui/configuration_controller.rb
class Webui::ConfigurationController < Webui::WebuiController
  before_filter :require_admin
  before_filter :set_configuration, only: [:update]
  before_filter :require_available_architectures, only: [:index]

  def index; end

  def interconnect; end

  def create_interconnect
    @project = RemoteProject.new(project_params)

    if @project.valid? && @project.store
      flash[:notice] = "Project '#{@project.name}' was created successfully"
      logger.debug "New remote project with url #{@project.remoteurl}"
      redirect_to controller: :project, action: 'show', project: @project.name
    else
      redirect_to :back, error: "Project can't be saved: #{@project.errors.full_messages.to_sentence}"
    end
  end

  def update
    respond_to do |format|
      if @configuration.update(configuration_params)
        format.html { redirect_to configuration_path, notice: 'Configuration was successfully updated.' }
      else
        format.html { redirect_to :back, error: "Configuration can't be saved: #{@configuration.errors.full_messages.to_sentence}" }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :title, :remoteurl, :description)
    end

    def configuration_params
      params.require(:configuration).permit(:name, :title, :description)
    end

    def set_configuration
      @configuration = ::Configuration.first
    end
end

src/api/app/views/webui/attribute/_attributes.html.erb
<% if @attributes.blank? %>
    <p><em>No attributes set</em></p>
<% else %>
    <div>
      <table>
        <tr>
          <th>Attribute</th>
          <th>Values</th>
          <% unless User.current.is_nobody? %>
              <th>Actions</th>
          <% end %>
        </tr>
        <% @attributes.each do |attribute| %>
            <tr class='attribute-values'>
              <td class='<%= "#{attribute.namespace}-#{attribute.name}" %>'><%= attribute.fullname %></td>
              <td class="<%= "#{attribute.namespace}-#{attribute.name}-values" %>">
                <%= attribute.values.map{ |a| a.value }.join(', ') %>
                <%= attribute.issues.map{ |i| i.name }.join(', ') %>
              </td>
              <% unless User.current.is_nobody? %>
                  <td>
                    <%= link_to(sprite_tag('note_edit', title: 'Edit values'),
                                edit_attribs_path(:project => @project.name, :package => @package, :attribute => attribute.fullname),
                                class: 'edit-values') if attribute.values_editable? %>
                    <%= button_to('Delete attribute', attrib_path(attribute),
                                  { data: { confirm: "Really remove attribute '#{attribute.fullname}'?" },
                                    method: :delete, class: 'delete-attribute', id: "#{attribute.namespace}-#{attribute.name}-delete", title: "Delete" }) %>
                  </td>
              <% end %>
            </tr>
        <% end %>
      </table>
    </div>
<% end %>

<% unless User.current.is_nobody? %>
    <p>
      <%= link_to(sprited_text('note_add', 'Add a new attribute'),
                  new_attribs_path(:project => @project.name, :package => @package),
                  id: 'add-new-attribute') %>
    </p>
<% end %>

src/api/app/views/webui/attribute/_form.html.erb
<%= form_for(@attribute) do |attribute_form| %>
  <% if @attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attribute.errors.count, "error") %> prohibited this attribute from being saved:</h2>
      <ul>
      <% @attribute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="values">
    <%= attribute_form.fields_for :values do |value| %>
      <%= render 'value_fields', :f => value %>
    <% end %>
    <% if @attribute.values_addable? %>
      <div class="links">
        <p>
          <%= link_to_add_association 'add value', attribute_form, :values %>
        </p>
      </div>
    <% end -%>
  </div>

  <% if @attribute.attrib_type.issue_list %>
    <div id="issues">
      <%= attribute_form.fields_for :issues do |issue| %>
        <%= render 'issue_fields', :f => issue %>
      <% end %>
    </div>
    <div class="links">
      <%= link_to_add_association 'add issue', attribute_form, :issues %>
    </div>
  <% end -%>

  <div class="actions">
    <%= attribute_form.hidden_field(:attrib_type_id) %>
    <p>
      <%= attribute_form.submit "Save Attribute" %>
    </p>
  </div>
<% end %>

src/api/app/views/webui/attribute/_issue_fields.html.erb
<div class="nested-fields">
  <div class="field">
    <%= f.select :issue_tracker_id, IssueTracker.all.collect { |tracker| [ tracker.name, tracker.id ] }.sort, include_blank: false %>
    <%= f.label :id %>
    <%= f.text_field :name %>
    <%= link_to_remove_association "remove issue", f %>
  </div>
</div>

src/api/app/views/webui/attribute/_value_fields.html.erb
<div class="nested-fields">
  <div class="field">
  <p>
    <% if @attribute.values_addable? %>
      <%= f.label :position %>
      <%= f.number_field :position, class: "attrib-position-input", size: 3 %>
    <% end -%>
    <%= f.label :value %>
    <% if @attribute.attrib_type.allowed_values.any? %>
      <%= f.select :value, @attribute.attrib_type.allowed_values.collect { |a| a.value }, {include_blank: false}, {id: 'attrib-default-select'} %>
    <% else %>
      <%= f.text_field :value %>
    <% end -%>
    <% if @attribute.values_removeable? %>
      <%= link_to_remove_association "remove value", f %>
    <% end -%>
  </p>
  </div>
</div>

src/api/app/views/webui/attribute/edit.html.erb
<% @pagetitle = "Edit Attribute #{@attribute.fullname} on #{@container.class} #{@container.name}" %>
<% project_bread_crumb
  if @package
    @crumb_list << link_to(@package, package_show_path(package: @package))
    @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name, package: @package))
  else
    @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name))
  end
  @crumb_list << @attribute.fullname %>

<% if @package %>
  <%= render :partial => "webui/package/tabs" %>
<% else %>
  <%= render :partial => "webui/project/tabs" %>
<% end %>

<h2><%= @pagetitle %></h2>
<p><%= @attribute.attrib_type.description %></p>
  <% if @attribute.values_editable? %>
    <%= render 'form' %>
  <% else -%>
    <p>This attribute has no values to edit</p>
  <% end -%>

src/api/app/views/webui/attribute/index.html.erb
<% @pagetitle = "Attributes" %>
<% project_bread_crumb
  if @package
    @crumb_list << link_to(@package, package_show_path(package: @package))
  end
  @crumb_list << "Attributes" %>

<% if @package %>
  <%= render :partial => "webui/package/tabs" %>
<% else %>
  <%= render :partial => "webui/project/tabs" %>
<% end %>

<%= render :partial => "attributes" %>

src/api/app/views/webui/attribute/new.html.erb
<% @pagetitle = "Add Attribute" %>
<% project_bread_crumb
  if @package
    @crumb_list << link_to(@package, package_show_path(package: @package))
    @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name, package: @package))
  else
    @crumb_list << link_to('Attributes', index_attribs_path(project: @project.name))
  end
  @crumb_list << "Add" %>

<% if @package %>
  <%= render :partial => "webui/package/tabs" %>
<% else %>
  <%= render :partial => "webui/project/tabs" %>
<% end %>

<h2><%= @pagetitle %></h2>
<%= form_for(@attribute) do |f| %>
  <div class="field">
    <p>
      <%= f.select :attrib_type_id, AttribType.all.collect { |a| [ a.fullname, a.id] }.sort, include_blank: false %>
      <%= hidden_field_tag("attrib[project_id]", @attribute.project_id) %>
      <%= hidden_field_tag("attrib[package_id]", @attribute.package_id) if @attribute.package_id %>
    </p>
  </div>
  <p class="help-block" id ="first-help">
    <%= AttribType.all.to_a.sort_by { |t| t.fullname }.first.description %>
    <%= "Sorry, this attribute has no description" if AttribType.all.to_a.sort_by { |t| t.fullname }.first.description.blank? %>
  </p>
  <% AttribType.all.each do |type| %>
    <p class="help-block attrib-type" id ="<%= type.id %>-help">
      <%= type.description %>
      <%= "Sorry, this attribute has no description" if type.description.blank? %>
    </p>
  <% end -%>
  <div class="actions">
  <p>
    <%= f.submit "Create Attribute" %>
  </p>
  </div>
<% end %>